# Generated by Django 5.2.4 on 2025-07-19 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('1', '低'), ('2', '中'), ('3', '高')], default='2', max_length=10)),
                ('memo', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
